
from os import getenv as ge
from constants import _SECRET_JSON_PATH, _TIMEZONE, _TABLE_OF_CONTENTS_CAPTION

TIMEZONE = ge("TIMEZONE", default=_TIMEZONE)
SECRET_JSON_PATH = ge("SECRET_JSON_PATH", default=_SECRET_JSON_PATH)
TABLE_OF_CONTENTS_CAPTION = ge("TABLE_OF_CONTENTS_CAPTION", default=_TABLE_OF_CONTENTS_CAPTION)
